### ISSUE TITLE
2018秋季-12-13周-盛晨曦

### ISSUE THREAD

**Issue by ShBj** [UCE-group/fortnightly-plan#126]
Recently l found that the Python has a function called 'Turtle',which can draw some vector diagrams.So I use it to draw some stars and draw the flag of the PRC.
I'll continue to learn Python from your PDF.Next 2 weeks I'll learn next chapter.

**Comment by xundaoxd** [comment]
Maybe you can draw pixel one by one.

**Comment by ShBj** [comment]
For 50 times?
