### ISSUE TITLE
我想请教一下WIN API的问题....

### ISSUE THREAD

**Issue by Changanzy** [UCE-group/fortnightly-plan#227]
#include <windows.h>
#include <stdio.h>
#include <string>
#include <math.h>
struct daxiao
	{
		int low;
		int high;
		double p;
	};
DWORD WINAPI Thread1(PVOID pvParam)
{
	int i;
	double sum=0.0,pi;
	daxiao* dx=(daxiao*) pvParam;
	int low=dx->low;
	int high=dx->high;
	for(i=low;i<high;i++)
		sum+=1.0/(i*i);
	pi=sqrt(sum*6);
	dx->p=pi;
	return 0;
}
int main()
{	
	daxiao qw1,qw2;
	qw1.low=1;
	qw1.high =1001;
    HANDLE ThreadHandle1= CreateThread(NULL,0,Thread1,&qw1,0,NULL);
	qw2.low=1001;
	qw2.high=2001;
	HANDLE ThreadHandle2 = CreateThread(NULL,0,Thread1,&qw2,0,NULL);
	HANDLE ThreadHandles[2]= {ThreadHandle1,ThreadHandle2};
	WaitForMultipleObjects(2,ThreadHandles,TRUE,INFINITE);
	double sum1,sum2,c;
	sum1=qw1.p;
	sum2=qw2.p;
	c=sum1+sum2;
	printf("%lf",c);
	return 0;
}
*### *这个可以运行，结果...有点奇怪，可能是我计算方法错了，计算的PI居然是3.19....不过这不是大问题，大问题是我加一个线程，运行结果直接就不对了**；
#include <windows.h>
#include <stdio.h>
#include <string>
#include <math.h>
struct daxiao
	{
		int low;
		int high;
		double p;
	};
DWORD WINAPI Thread1(PVOID pvParam)
{
	int i;
	double sum=0.0,pi;
	daxiao* dx=(daxiao*) pvParam;
	int low=dx->low;
	int high=dx->high;
	for(i=low;i<high;i++)
		sum+=1.0/(i*i);
	pi=sqrt(sum*6);
	dx->p=pi;
	return 0;
}
int main()
{	
	daxiao qw1,qw2,qw3;
	qw1.low=1;
	qw1.high =1001;
    HANDLE ThreadHandle1= CreateThread(NULL,0,Thread1,&qw1,0,NULL);
	qw2.low=1001;
	qw2.high=2001;
	HANDLE ThreadHandle2= CreateThread(NULL,0,Thread1,&qw2,0,NULL);
	qw1.low=2001;
	qw1.high =3001;
    HANDLE ThreadHandle3= CreateThread(NULL,0,Thread1,&qw3,0,NULL);
	HANDLE ThreadHandles[3]= {ThreadHandle1,ThreadHandle2,ThreadHandle3};
	WaitForMultipleObjects(3,ThreadHandles,TRUE,INFINITE);
	double sum1,sum2,sum3;
	sum1=qw1.p;
	sum2=qw2.p;
	sum3=qw3.p;
	printf("%lf",sum1+sum2+sum3);
	return 0;
}
**在线蹲一个大佬讲解...**

**Comment by zhiye1070534263** [comment]
我知道我哪里错了....打扰了

**Comment by lifuguan** [comment]
多核程序设计.jpg
